version: '3'
services:
  db:
    image: mysql:latest
    ports: 
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/sql:/docker-entrypoint-initdb.d
      - ./mysql/mysql_conf:/etc/mysql/conf.d
      
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: web_app
      MYSQL_USER: taiki
      MYSQL_PASSWORD: password
    
  php:
    build: ./php
    #build: ./php-fpm
    image: php:7.4-fpm
    depends_on: 
      - db
    container_name: webapp_php_1
    # ports:
    # # こちらの8080を8079や8081などの値に変更してくださいよぉぉぉぉぉぉ???????。
    # - "8080:8000"
    volumes:
    - ./html:/var/www/html
    # - ./php/php.ini:/usr/local/etc/php/php.ini
    

  nginx:
    image: nginx:latest
    depends_on: 
      - php
    ports: 
      - "84:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./html:/var/www/html
  
